name: Quality Control
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]
    paths-ignore:
      - "**/*.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  go-qc:
    name: Go Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: true
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Fix formatting with gofumpt
        run: |
          cd decaf-reference/
          gofumpt -l -w .
      - name: Run staticcheck
        run: |
          cd decaf-reference/
          staticcheck ./...
      - name: Run go vet
        run: |
          cd decaf-reference
          go vet ./...
      - name: Run golint
        run: |
          go install golang.org/x/lint/golint@latest
          cd decaf-reference
          golint -set_exit_status ./...

  rust-qc:
    name: Rust Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Fix formatting decaf
        run: |
          cd decaf
          cargo fmt --all
      - name: Run clippy on decaf
        run: |
          cd decaf
          cargo clippy --fix --all-features -- -D warnings
      - name: Run tests on decaf
        run: |
          cd decaf
          cargo test --all-features
      - name: Fix formatting decaf-cli
        run: |
          cd decaf-cli
          cargo fmt --all
      - name: Run clippy on decaf-cli
        run: |
          cd decaf-cli
          cargo clippy --fix --all-features -- -D warnings
      - name: Run tests on decaf-cli
        run: |
          cd decaf-cli
          cargo test --all-features
      - name: Fix formatting dtar
        run: |
          cd dtar
          cargo fmt --all
      - name: Run clippy on dtar
        run: |
          cd dtar
          cargo clippy --fix --all-features -- -D warnings
      - name: Run tests on dtar
        run: |
          cd dtar
          cargo test --all-features

  commit:
    name: Commit quality control changes
    needs: [go-qc, rust-qc]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git config --global user.name 'decaf-qc[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet || (git add . && git commit -m "all: automated quality control" && git push)
