name: Quality Control
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]
    paths-ignore:
      - "**/*.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  go-qc:
    name: Go Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: true
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run `go mod tidy`
        if: always()
        run: |
          cd decaf-reference/
          go mod tidy
      - name: Fix formatting with gofumpt
        if: always()
        run: |
          cd decaf-reference/
          gofumpt -l -w .
      - name: Run staticcheck
        if: always()
        run: |
          cd decaf-reference/
          staticcheck ./...
      - name: Run go vet
        if: always()
        run: |
          cd decaf-reference
          go vet ./...

  rust-qc:
    name: Rust Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Fix formatting decaf
        run: |
          cd decaf
          cargo fmt --all
      - name: Run clippy on decaf
        if: always()
        run: |
          cd decaf
          cargo clippy --fix --allow-dirty --all-features -- -D warnings
      - name: Run tests on decaf
        if: always()
        run: |
          cd decaf
          cargo test --all-features
      - name: Fix formatting decaf-cli
        if: always()
        run: |
          cd decaf-cli
          cargo fmt --all
      - name: Run clippy on decaf-cli
        if: always()
        run: |
          cd decaf-cli
          cargo clippy --fix --allow-dirty --all-features -- -D warnings
      - name: Run tests on decaf-cli
        if: always()
        run: |
          cd decaf-cli
          cargo test --all-features
      - name: Fix formatting dtar
        if: always()
        run: |
          cd dtar
          cargo fmt --all
      - name: Run clippy on dtar
        if: always()
        run: |
          cd dtar
          cargo clippy --fix --allow-dirty --all-features -- -D warnings
      - name: Run tests on dtar
        if: always()
        run: |
          cd dtar
          cargo test --all-features

  commit:
    name: Commit quality control changes
    needs: [go-qc, rust-qc]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
